language: php
sudo: false
dist: trusty
php:
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - ./vendor/bin/phpunit
  - ./bin/drutiny profile:list

# Configure email notifications
notifications:
  email:
    on_success: never
    on_failure: always
