language: php
sudo: false
dist: trusty
php:
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit

# Configure email notifications
notifications:
  email:
    on_success: never
    on_failure: always
