metadata :
  machine_name: 'default'
  title : 'Site audit (Drupal 7)'
checks :
  \SiteAudit\Check\Drush\ModuleEnabled:
    modules:
      - syslog
      - acquia_spi
      - acquia_agent
  \SiteAudit\Check\Drush\ModuleDisabled:
    modules:
      - backup_migrate
      - dblog
      - devel
      - linkchecker
      - overlay
      - php
      - radioactivity
      - smart_ip
      - statistics
      - simpletest
      - textsize
      - update
  \SiteAudit\Check\D7\PreprocessCSS : {}
  \SiteAudit\Check\D7\PreprocessJS : {}
  \SiteAudit\Check\D7\UserRegister : {}
  \SiteAudit\Check\D7\PageCacheMaximumAge :
    cache : 300
  \SiteAudit\Check\Codebase\HtaccessRedirects :
    max_redirects : 10
  \SiteAudit\Check\Drush\UpdateDBStatus: {}
  \SiteAudit\Check\D7\Search404: {}
  \SiteAudit\Check\D7\SearchDB: {}
  \SiteAudit\Check\Drush\SessionsAnon: {}
  \SiteAudit\Check\D7\CronHasRun: {}
  \SiteAudit\Check\D7\CronPoorMans: {}
  \SiteAudit\Check\D7\PageCompression: {}
  \SiteAudit\Check\D7\ZenRebuildRegistry: {}
  \SiteAudit\Check\D7\XMLSiteMapBaseUrl:
    pattern : '^https?://[-a-z]{1,63}\.[-a-z]{1,63}\.com\.au$'
