metadata :
  machine_name: 'default'
  title : 'Site audit'
checks :
  \SiteAudit\Check\Drush\ModuleEnabled:
    modules:
      - syslog
  \SiteAudit\Check\Drush\ModuleDisabled:
    modules:
      - dblog
      - overlay
      - php
      - statistics
  \SiteAudit\Check\Drush\PreprocessCSS : {}
  \SiteAudit\Check\Drush\PreprocessJS : {}
  \SiteAudit\Check\Drush\PageCacheMaximumAge :
    cache : 300
  \SiteAudit\Check\Drush\UpdateDBStatus: {}
  \SiteAudit\Check\HtaccessRedirects :
    max_redirects : 8
